name: Build app

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-14, windows-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.14.0'
        cache: 'npm'
    - name: Install pnpm
      run: npm install -g pnpm
    
    - name: Configure pnpm
      run: pnpm config set store-dir .pnpm-store

    - name: Install dependencies
      run: pnpm install

    - name: Build
      run: pnpm run package

    - name: Build app
      run: pnpm run make
